# Generated by Django 5.0.6 on 2024-07-12 14:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', upload_to=core.models.avatar_upload_to),
        ),
    ]
